### ISSUE TITLE
pslurp bug: different servers with same public ip address and different ssh port will cause bug

### ISSUE THREAD

**Issue by pengqi** [lilydjwg/pssh#106]
e.g. 
There are following three servers, they have same public ip address, but different ssh port.
202.117.112.10:22
202.117.112.10:222
202.117.112.10:223

If use pslurp, only one  local "202.117.112.10" directory will be created. Then the files from first two servers will be missing.

**Comment by lilydjwg** [comment]
I've merged your patch. Thanks!
