### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by jspricke** [lilydjwg/pssh#112]
Hi,

thanks for taking care of pssh. I'm in the process of adopting the Debian package of it and would like to switch to your repo as upstream. There is a commit for a 2.3.3 version in c6954966d0c9479abe15e66cf636812864c8d22f, but it was not tagged and thus is not shown on https://github.com/lilydjwg/pssh/releases. Could you please do that so I can import it into Debian?

Thanks!

P.S. Creating a new version from the latest master would be even better :).

**Comment by lilydjwg** [comment]
I've tagged version 2.3.4 from master.
