### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by ServerMonkey** [lilydjwg/pssh#116]
I use parallel-ssh almost everyday. Say I run it 10 times a day on 50+ servers.
To 95% of the time this works just fine. But within regular intervals the program crashes and gives the same error:

```
Traceback (most recent call last):
  File "/usr/bin/parallel-ssh", line 118, in <module>
    do_pssh(hosts, cmdline, opts)
  File "/usr/bin/parallel-ssh", line 89, in do_pssh
    statuses = manager.run()
  File "/usr/lib/python2.7/dist-packages/psshlib/manager.py", line 75, in run
    self.update_tasks(writer)
  File "/usr/lib/python2.7/dist-packages/psshlib/manager.py", line 132, in update_tasks
    self.clear_sigchld_handler()
  File "/usr/lib/python2.7/dist-packages/psshlib/manager.py", line 95, in clear_sigchld_handler
    signal.signal(signal.SIGCHLD, signal.SIG_DFL)
TypeError: 'int' object is not callable
```
The only workaround I have is to run the same command again and it works just fine the second time.

I'm on Debian 10 x64 and use the stable package pssh 2.3.1-1 with python 2.7.16-2+deb10u1.
For example I use pssh like this to shutdown all nodes in a cluster:
```
file=nodes.txt  # my list of nodes
log=log.ini
parallel-ssh -p 1 -h $file -t 0 -l myusername -O StrictHostKeyChecking=accept-new -i 'shutdown -r now ; echo "############################" ' > $log
```

I'm not sure who to report this issue to. To the Debian package maintainer or here? On the other hand there could be a problem in the Python or the SSL lib, dunno...
Does anyone know?
I can always help to run tests in a bigger environment.

**Comment by lilydjwg** [comment]
This seems to be the same problem as #115. Could you try master?

**Comment by ServerMonkey** [comment]
Installed it, will test it over the week.

**Comment by ServerMonkey** [comment]
The bug is gone in master, as far as my tests go. Closed.
