### ISSUE TITLE
How do I copy files from multiple hosts to local using parallel-rsync?

### ISSUE THREAD

**Issue by Dweller** [lilydjwg/pssh#120]
Its not clear to me how you use parallel-rsync to copy files from multiple hosts to local?

Could somebody give me an example?

Thanks in advance?

**Comment by lilydjwg** [comment]
```sh
pslurp -h ~/etc/hosts -L out /etc/resolv.conf resolv.conf
```

**Comment by Dweller** [comment]
> ```shell
> pslurp -h ~/etc/hosts -L out /etc/resolv.conf resolv.conf
> ```

Thanks but I need to repeatably parse a recursive directory tree with GB's of data so I need to use rsync rather than scp..

**Comment by lilydjwg** [comment]
Oh. It probably is not supported.

**Comment by lilydjwg** [comment]
I've added an argument to support downloading. The output path is `<last_arg>/<host>/<contents>`. I hope it works for you.
