### ISSUE TITLE
PSCP - StrictHostKeyChecking 

### ISSUE THREAD

**Issue by saisro** [lilydjwg/pssh#124]
Hello,

Is it possible to set the "StrictHostKeyChecking=no" option to pscp? If not, do you have a solution? Thanks.

**Comment by lilydjwg** [comment]
Try to add `-o StrictHostKeyChecking=no`?

**Comment by saisro** [comment]
No, it doesn't work.

**Comment by saisro** [comment]
It works with the option -x "-o StrictHostKeyChecking=no"  and not -O.
