### ISSUE TITLE
tilestamp + SUCCESS/ERROR header should goes to stderr not stdout

### ISSUE THREAD

**Issue by gpion** [lilydjwg/pssh#131]
Hello,
pssh outputs are prefixed by that kind of headers:
`[1] HH:MM:SS [SUCCESS] <hostname>`

I think those message should be output to stderr, not stdout as it currently does

When using this:
`pssh <arg< --inline-stdout <remote command> > <file>`

the <file> contains those headers mixed with usable output from command

**Comment by lilydjwg** [comment]
Why do you think removing those headers makes the output usable? You wouldn't know which host the output comes from.

If you want raw output from the command, you can use the `-o directory` argument.

**Comment by gpion** [comment]
> Why do you think removing those headers makes the output usable?

Because headers are not part of the actual output from the remote(s) hosts(s).
Just think to that simple case where the purpose is to process the concatenated output of the remote command:
`pssh -H "host1 host2 ..." --inline-stdout <remote command> | <process data>`

> If you want raw output from the command, you can use the `-o directory` argument.

This create a separate file for each host, and would not apply to the case where pssh is used in a pipeline like above (pssh ... | <process data>) which is a current use case.

A better option (and which will preserve upward compatibility which is important) could be to add a "--quiet" or "--noheaders" command switch to "pssh" command.

**Comment by gpion** [comment]
Oh I forgot, about stderr/stdout confusion there is an old but I think still valid clarification there:
[When to use STDERR instead of STDOUT](https://web.archive.org/web/20201204114029/http://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout)

**Comment by lilydjwg** [comment]
A `--no-headers` option has been added.

**Comment by gpion** [comment]
Great!
Thanks.
