### ISSUE TITLE
pssh not support IPV6 address

### ISSUE THREAD

**Issue by BoynChan** [lilydjwg/pssh#136]
In this file, I found that pssh will only resolve single IPV4 address https://github.com/lilydjwg/pssh/blob/13995275fb163cbfc4ed42c63de594930ed68678/psshlib/psshutil.py#L90.

And it's not gonna work if I passed IPV6 hosts

**Comment by lilydjwg** [comment]
Fixed. IPv6 addresses need to be enclosed in `[ ]` as in other URLs.
