### ISSUE TITLE
urllib.parse.urlparse  return a int port in 2.3.5 and master

### ISSUE THREAD

**Issue by chaolmrrt** [lilydjwg/pssh#141]
![image](https://github.com/lilydjwg/pssh/assets/51053552/e3d98768-3ffd-4dcf-b77b-2603be6cae2e)

![image](https://github.com/lilydjwg/pssh/assets/51053552/6a12f673-089f-4821-8020-9f4ad80884ae)

**Comment by lilydjwg** [comment]
This has been fixed in master. Please make sure you use the right files.
